import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('qoot-language');
    return saved || 'en';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    localStorage.setItem('qoot-language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    nav: {
      problem: 'Problem',
      solution: 'Solution',
      features: 'Features',
      pricing: 'Pricing',
      roadmap: 'Roadmap',
      contact: 'Contact',
      requestDemo: 'Request Demo',
    },
    hero: {
      badge: 'Launching in New Cairo & Madinaty',
      tagline: 'Smart Menus. Smart Payments. Smarter Dining.',
      description: 'The complete digital dining ecosystem for Egyptian restaurants. Transform your customer experience from order to payment.',
      requestDemo: 'Request a Demo',
      seeHow: 'See How It Works',
      fasterTurnover: 'Faster Turnover',
      higherRevenue: 'Higher Revenue',
      costSavings: 'Cost Savings',
      scrollToExplore: 'Scroll to explore',
    },
    problem: {
      badge: 'The Challenge',
      title: 'The Chaos of Traditional Dining',
      description: 'Running a restaurant in Egypt today involves juggling overwhelmed staff, outdated paper menus, and payment bottlenecks. These friction points don\'t just annoy customers - they cost you money.',
      overwhelmedStaff: 'Overwhelmed Staff',
      overwhelmedStaffDesc: 'Staff are overwhelmed during peak hours, leading to service errors and unhappy customers.',
      slowTurnover: 'Slow Table Turnover',
      slowTurnoverDesc: 'Guests wait too long for the bill, reducing your daily covers and revenue potential.',
      expensiveMenus: 'Expensive Menu Updates',
      expensiveMenusDesc: 'Reprinting paper menus every time prices change drains your budget unnecessarily.',
      noData: 'No Real Data',
      noDataDesc: 'You lack real data on what is actually selling, making decisions based on guesswork.',
      soundFamiliar: 'Sound familiar? There\'s a better way.',
      seeSolution: 'See the Solution',
    },
    solution: {
      badge: 'The Solution',
      title: 'The Qoot Ecosystem',
      description: 'Qoot is not just a digital menu. It\'s an all-in-one operating system for your dining room that digitizes the entire customer journey from the moment they sit down.',
      scan: 'SCAN',
      scanDesc: 'Guests scan a QR code at their table to access your digital menu instantly.',
      order: 'ORDER',
      orderDesc: 'Orders are sent directly to the kitchen or bar with perfect accuracy.',
      enjoy: 'ENJOY',
      enjoyDesc: 'Guests dine without interruption while you focus on hospitality.',
      pay: 'PAY',
      payDesc: 'Bill is settled instantly via phone - no waiting, no hassle.',
      analyze: 'ANALYZE',
      analyzeDesc: 'Get actionable insights on your dashboard in real-time.',
      fromSeated: 'From seated to satisfied in',
      simpleSteps: '5 Simple Steps',
    },
    features: {
      badge: 'Features',
      title: 'Everything You Need to Transform Your Restaurant',
      description: 'A complete suite of tools designed for modern Egyptian restaurants. Click any feature to learn more.',
      digitalMenu: 'Digital QR Menu',
      digitalMenuTag: 'Dynamic & Beautiful',
      digitalMenuDesc: 'Say goodbye to worn-out paper. Our digital menus are vibrant, easy to update, and designed to make your food look irresistible.',
      smartOrdering: 'Smart Ordering',
      smartOrderingTag: 'Direct-to-Kitchen Accuracy',
      smartOrderingDesc: 'Eliminate the "he said, she said" errors. When customers order from their phones, they get exactly what they want.',
      payments: 'Table-Side Payments',
      paymentsTag: 'Frictionless Checkout',
      paymentsDesc: 'The biggest bottleneck in dining is waiting for the check. Qoot removes this entirely.',
      ar: 'AR Experience',
      arTag: 'Visualize Before You Eat',
      arDesc: 'Stand out with Augmented Reality. Guests project a 3D model of the dish onto their table using their camera.',
      analytics: 'Business Analytics',
      analyticsTag: 'Data-Driven Decisions',
      analyticsDesc: 'Stop guessing. Start knowing. Our dashboard gives you a live pulse on your restaurant\'s performance.',
      localized: 'Localized for Egypt',
      localizedTag: 'Built for the Local Market',
      localizedDesc: 'We understand the nuances of the Egyptian market and have built our solution specifically for it.',
      clickToLearn: 'Click to learn more',
      premium: 'PREMIUM',
    },
    value: {
      badge: 'Value for Owners',
      title: 'ROI You Can Measure',
      description: 'Qoot isn\'t an expense; it\'s an investment that pays for itself. See the projected impact on your business.',
      turnover: 'Increase in Table Turnover',
      turnoverDesc: 'Faster checkout means more covers per night',
      ticket: 'Higher Average Ticket Size',
      ticketDesc: 'Smart upselling suggestions boost revenue',
      labor: 'Reduction in Labor Costs',
      laborDesc: 'Optimize staff efficiency with automation',
      quote: '"Traditional systems are fragmented. Qoot unifies them."',
    },
    pricing: {
      badge: 'Pricing',
      title: 'Flexible SaaS for Every Stage',
      description: 'Choose the plan that fits your restaurant\'s needs. All plans include our core digital dining technology.',
      starter: 'STARTER',
      starterTag: 'Menu Only',
      starterDesc: 'Perfect for cafes needing quick digital menus.',
      pro: 'PRO',
      proTag: 'Full Suite',
      proDesc: 'Best for busy restaurants with high volume.',
      enterprise: 'ENTERPRISE',
      enterpriseTag: 'Premium Experience',
      enterpriseDesc: 'For chains and luxury dining establishments.',
      contactUs: 'Contact Us',
      custom: 'Custom',
      getStarted: 'Get Started',
      contactSales: 'Contact Sales',
      mostPopular: 'Most Popular',
      needCustom: 'Need a custom solution?',
      contactForPricing: 'Contact us for enterprise pricing',
      features: {
        qrCode: 'QR Code generation',
        menuManagement: 'Digital Menu Management',
        basicCustomization: 'Basic customization',
        upTo50Items: 'Up to 50 menu items',
        emailSupport: 'Email support',
        everythingStarter: 'Everything in Starter',
        smartOrdering: 'Smart Ordering System',
        tableSidePayments: 'Table-Side Payments',
        basicAnalytics: 'Basic Analytics Dashboard',
        unlimitedItems: 'Unlimited menu items',
        prioritySupport: 'Priority support',
        staffTraining: 'Staff training included',
        everythingPro: 'Everything in Pro',
        arMenu: 'AR Menu Visualization',
        aiRecommendations: 'AI Recommendations',
        apiAccess: 'API Access',
        advancedAnalytics: 'Advanced Analytics',
        multiLocation: 'Multi-location support',
        dedicatedManager: 'Dedicated account manager',
        customIntegrations: 'Custom integrations',
      },
    },
    roadmap: {
      badge: 'Roadmap',
      title: 'Building for the Future',
      description: 'Our vision extends beyond New Cairo. Here\'s how we\'re planning to revolutionize dining across Egypt.',
      q1: 'Q1 2025',
      q1Title: 'MVP Launch',
      q1Desc: 'Launch in New Cairo & Madinaty with core features',
      q2: 'Q2 2025',
      q2Title: 'Inventory Integration',
      q2Desc: 'Advanced inventory management and supplier connections',
      q3: 'Q3 2025',
      q3Title: 'AI Personalization',
      q3Desc: 'AI-driven customer personalization and recommendations',
      q4: 'Q4 2025',
      q4Title: 'Coastal Expansion',
      q4Desc: 'Expansion to premium vacation destinations',
      currentlyActive: 'Currently Active',
      newCairo: 'New Cairo',
      madinaty: 'Madinaty',
      sahel: 'Sahel',
      gouna: 'Gouna',
      bePartOf: 'Be part of the dining revolution from day one.',
      joinEarly: 'Join Our Early Adopter Program',
    },
    localization: {
      badge: 'Built for Egypt',
      title: 'Localized for the Egyptian Market',
      description: 'We understand the nuances of the Egyptian hospitality industry. Qoot is not a foreign solution adapted for Egypt - it\'s built from the ground up for Egyptian restaurants.',
      arabicSupport: 'Arabic Support',
      paymentMethods: 'Local Payment Methods',
      bilingual: 'Fully Bilingual',
      bilingualDesc: 'Complete Arabic and English interface for both customers and staff.',
      bilingualTag: 'عربي / English',
      payment: 'Local Payment Integration',
      paymentDesc: 'Seamlessly integrated with InstaPay, Fawry, and local bank cards.',
      paymentTag: 'InstaPay • Fawry • Visa',
      whatsapp: 'WhatsApp Support',
      whatsappDesc: 'Direct WhatsApp support for restaurant owners. Get help when you need it.',
      whatsappTag: '24/7 Support',
      compliance: 'Local Compliance',
      complianceDesc: 'Fully compliant with Egyptian regulations and data protection laws.',
      complianceTag: 'Egypt Compliant',
      integratedWith: 'Integrated with local payment providers',
    },
    contact: {
      badge: 'Get Started',
      title: 'Transform Your Restaurant Today',
      description: 'Don\'t let outdated systems hold your business back. Join the dining revolution and see how Qoot can transform your customer experience.',
      freeDemo: 'Free demo and consultation',
      noCommitment: 'No commitment required',
      customSolution: 'Custom solution for your needs',
      localSupport: 'Local support in Arabic & English',
      preferDirect: 'Prefer to reach out directly?',
      email: 'Email:',
      whatsapp: 'WhatsApp:',
      formTitle: 'Request a Demo',
      restaurantName: 'Restaurant Name',
      restaurantPlaceholder: 'e.g., Cairo Grill House',
      yourName: 'Your Name',
      namePlaceholder: 'Your full name',
      emailLabel: 'Email',
      emailPlaceholder: 'you@email.com',
      phone: 'Phone',
      phonePlaceholder: '+20 1XX XXX XXXX',
      location: 'Location',
      selectLocation: 'Select your location',
      message: 'Message (Optional)',
      messagePlaceholder: 'Tell us about your restaurant and what you\'re looking for...',
      submit: 'Request Demo',
      submitting: 'Submitting...',
      agreement: 'By submitting, you agree to be contacted by the Qoot team.',
      thankYou: 'Thank You!',
      thankYouDesc: 'We\'ve received your request and will contact you within 24 hours.',
      submitAnother: 'Submit another request',
      required: '*',
    },
    footer: {
      tagline: 'Transforming hospitality in Egypt with smart digital dining solutions. Smart Menus. Smart Payments. Smarter Dining.',
      quickLinks: 'Quick Links',
      contactUs: 'Contact Us',
      ceo: 'Ahmed Allam, CEO',
      location: 'New Cairo, Egypt',
      copyright: '© 2025 Qoot. All rights reserved.',
      bottomTagline: 'Transforming Hospitality in Egypt',
    },
  },
  ar: {
    nav: {
      problem: 'المشكلة',
      solution: 'الحل',
      features: 'المميزات',
      pricing: 'الأسعار',
      roadmap: 'خارطة الطريق',
      contact: 'تواصل معنا',
      requestDemo: 'اطلب عرض',
    },
    hero: {
      badge: 'الإطلاق في القاهرة الجديدة ومدينتي',
      tagline: 'قوائم ذكية. مدفوعات ذكية. تجربة طعام أذكى.',
      description: 'النظام الرقمي المتكامل لتجربة الطعام في المطاعم المصرية. حوّل تجربة عملائك من الطلب إلى الدفع.',
      requestDemo: 'اطلب عرض توضيحي',
      seeHow: 'شاهد كيف يعمل',
      fasterTurnover: 'دوران أسرع',
      higherRevenue: 'إيرادات أعلى',
      costSavings: 'توفير التكاليف',
      scrollToExplore: 'مرر للاستكشاف',
    },
    problem: {
      badge: 'التحدي',
      title: 'فوضى المطاعم التقليدية',
      description: 'إدارة مطعم في مصر اليوم تعني التعامل مع موظفين مرهقين، قوائم ورقية قديمة، واختناقات في الدفع. هذه المشاكل لا تزعج العملاء فحسب - بل تكلفك المال.',
      overwhelmedStaff: 'موظفون مرهقون',
      overwhelmedStaffDesc: 'الموظفون مرهقون خلال ساعات الذروة، مما يؤدي إلى أخطاء في الخدمة وعملاء غير راضين.',
      slowTurnover: 'بطء دوران الطاولات',
      slowTurnoverDesc: 'الضيوف ينتظرون طويلاً للحصول على الفاتورة، مما يقلل من عدد الزبائن اليومي.',
      expensiveMenus: 'تحديثات القائمة المكلفة',
      expensiveMenusDesc: 'إعادة طباعة القوائم الورقية في كل مرة تتغير فيها الأسعار يستنزف ميزانيتك.',
      noData: 'لا توجد بيانات حقيقية',
      noDataDesc: 'ليس لديك بيانات حقيقية عما يُباع فعلاً، وتتخذ قرارات بناءً على التخمين.',
      soundFamiliar: 'يبدو مألوفاً؟ هناك طريقة أفضل.',
      seeSolution: 'شاهد الحل',
    },
    solution: {
      badge: 'الحل',
      title: 'نظام قوت المتكامل',
      description: 'قوت ليس مجرد قائمة رقمية. إنه نظام تشغيل متكامل لصالة مطعمك يرقمن رحلة العميل بالكامل من لحظة جلوسه.',
      scan: 'امسح',
      scanDesc: 'يمسح الضيوف رمز QR على طاولتهم للوصول إلى قائمتك الرقمية فوراً.',
      order: 'اطلب',
      orderDesc: 'تُرسل الطلبات مباشرة إلى المطبخ أو البار بدقة تامة.',
      enjoy: 'استمتع',
      enjoyDesc: 'يتناول الضيوف طعامهم دون انقطاع بينما تركز أنت على الضيافة.',
      pay: 'ادفع',
      payDesc: 'يُسدد الحساب فوراً عبر الهاتف - بدون انتظار، بدون متاعب.',
      analyze: 'حلّل',
      analyzeDesc: 'احصل على رؤى قابلة للتنفيذ على لوحة التحكم في الوقت الفعلي.',
      fromSeated: 'من الجلوس إلى الرضا في',
      simpleSteps: '٥ خطوات بسيطة',
    },
    features: {
      badge: 'المميزات',
      title: 'كل ما تحتاجه لتحويل مطعمك',
      description: 'مجموعة كاملة من الأدوات المصممة للمطاعم المصرية الحديثة. انقر على أي ميزة لمعرفة المزيد.',
      digitalMenu: 'قائمة QR رقمية',
      digitalMenuTag: 'ديناميكية وجميلة',
      digitalMenuDesc: 'ودّع الورق البالي. قوائمنا الرقمية نابضة بالحياة، سهلة التحديث، ومصممة لجعل طعامك لا يُقاوم.',
      smartOrdering: 'طلب ذكي',
      smartOrderingTag: 'دقة مباشرة للمطبخ',
      smartOrderingDesc: 'تخلص من أخطاء "قال وقلت". عندما يطلب العملاء من هواتفهم، يحصلون بالضبط على ما يريدون.',
      payments: 'الدفع على الطاولة',
      paymentsTag: 'دفع سلس',
      paymentsDesc: 'أكبر عائق في تناول الطعام هو انتظار الفاتورة. قوت يزيل هذا تماماً.',
      ar: 'تجربة الواقع المعزز',
      arTag: 'شاهد قبل أن تأكل',
      arDesc: 'تميّز بالواقع المعزز. يعرض الضيوف نموذجاً ثلاثي الأبعاد للطبق على طاولتهم باستخدام كاميرتهم.',
      analytics: 'تحليلات الأعمال',
      analyticsTag: 'قرارات مبنية على البيانات',
      analyticsDesc: 'توقف عن التخمين. ابدأ بالمعرفة. لوحة التحكم تعطيك نبض مطعمك في الوقت الفعلي.',
      localized: 'مُعد لمصر',
      localizedTag: 'مبني للسوق المحلي',
      localizedDesc: 'نفهم تفاصيل السوق المصري وبنينا حلنا خصيصاً له.',
      clickToLearn: 'انقر لمعرفة المزيد',
      premium: 'مميز',
    },
    value: {
      badge: 'قيمة للمالكين',
      title: 'عائد استثمار قابل للقياس',
      description: 'قوت ليس مصروفاً؛ إنه استثمار يدفع ثمن نفسه. شاهد التأثير المتوقع على عملك.',
      turnover: 'زيادة في دوران الطاولات',
      turnoverDesc: 'الدفع الأسرع يعني المزيد من الزبائن كل ليلة',
      ticket: 'متوسط فاتورة أعلى',
      ticketDesc: 'اقتراحات البيع الذكية تعزز الإيرادات',
      labor: 'تخفيض تكاليف العمالة',
      laborDesc: 'حسّن كفاءة الموظفين بالأتمتة',
      quote: '"الأنظمة التقليدية مجزأة. قوت يوحدها."',
    },
    pricing: {
      badge: 'الأسعار',
      title: 'اشتراك مرن لكل مرحلة',
      description: 'اختر الخطة التي تناسب احتياجات مطعمك. جميع الخطط تشمل تقنية الطعام الرقمي الأساسية.',
      starter: 'المبتدئ',
      starterTag: 'القائمة فقط',
      starterDesc: 'مثالي للمقاهي التي تحتاج قوائم رقمية سريعة.',
      pro: 'الاحترافي',
      proTag: 'الباقة الكاملة',
      proDesc: 'الأفضل للمطاعم المزدحمة ذات الحجم الكبير.',
      enterprise: 'المؤسسات',
      enterpriseTag: 'تجربة متميزة',
      enterpriseDesc: 'للسلاسل ومؤسسات الطعام الفاخرة.',
      contactUs: 'تواصل معنا',
      custom: 'مخصص',
      getStarted: 'ابدأ الآن',
      contactSales: 'تواصل مع المبيعات',
      mostPopular: 'الأكثر شعبية',
      needCustom: 'تحتاج حلاً مخصصاً؟',
      contactForPricing: 'تواصل معنا لأسعار المؤسسات',
      features: {
        qrCode: 'توليد رمز QR',
        menuManagement: 'إدارة القائمة الرقمية',
        basicCustomization: 'تخصيص أساسي',
        upTo50Items: 'حتى 50 عنصر في القائمة',
        emailSupport: 'دعم بالبريد الإلكتروني',
        everythingStarter: 'كل ما في المبتدئ',
        smartOrdering: 'نظام الطلب الذكي',
        tableSidePayments: 'الدفع على الطاولة',
        basicAnalytics: 'لوحة تحليلات أساسية',
        unlimitedItems: 'عناصر غير محدودة',
        prioritySupport: 'دعم ذو أولوية',
        staffTraining: 'تدريب الموظفين مشمول',
        everythingPro: 'كل ما في الاحترافي',
        arMenu: 'قائمة الواقع المعزز',
        aiRecommendations: 'توصيات الذكاء الاصطناعي',
        apiAccess: 'وصول API',
        advancedAnalytics: 'تحليلات متقدمة',
        multiLocation: 'دعم المواقع المتعددة',
        dedicatedManager: 'مدير حساب مخصص',
        customIntegrations: 'تكاملات مخصصة',
      },
    },
    roadmap: {
      badge: 'خارطة الطريق',
      title: 'نبني للمستقبل',
      description: 'رؤيتنا تمتد إلى ما بعد القاهرة الجديدة. إليك كيف نخطط لتحويل تجربة الطعام في جميع أنحاء مصر.',
      q1: 'الربع الأول 2025',
      q1Title: 'إطلاق MVP',
      q1Desc: 'الإطلاق في القاهرة الجديدة ومدينتي بالميزات الأساسية',
      q2: 'الربع الثاني 2025',
      q2Title: 'تكامل المخزون',
      q2Desc: 'إدارة مخزون متقدمة وربط الموردين',
      q3: 'الربع الثالث 2025',
      q3Title: 'تخصيص الذكاء الاصطناعي',
      q3Desc: 'تخصيص العملاء والتوصيات بالذكاء الاصطناعي',
      q4: 'الربع الرابع 2025',
      q4Title: 'التوسع الساحلي',
      q4Desc: 'التوسع إلى وجهات العطلات المتميزة',
      currentlyActive: 'نشط حالياً',
      newCairo: 'القاهرة الجديدة',
      madinaty: 'مدينتي',
      sahel: 'الساحل',
      gouna: 'الجونة',
      bePartOf: 'كن جزءاً من ثورة تجربة الطعام من اليوم الأول.',
      joinEarly: 'انضم لبرنامج المتبنين الأوائل',
    },
    localization: {
      badge: 'مبني لمصر',
      title: 'مُعد للسوق المصري',
      description: 'نفهم تفاصيل صناعة الضيافة المصرية. قوت ليس حلاً أجنبياً مُعدّلاً لمصر - إنه مبني من الأساس للمطاعم المصرية.',
      arabicSupport: 'دعم العربية',
      paymentMethods: 'طرق الدفع المحلية',
      bilingual: 'ثنائي اللغة بالكامل',
      bilingualDesc: 'واجهة عربية وإنجليزية كاملة للعملاء والموظفين.',
      bilingualTag: 'عربي / English',
      payment: 'تكامل الدفع المحلي',
      paymentDesc: 'متكامل بسلاسة مع إنستاباي وفوري وبطاقات البنوك المحلية.',
      paymentTag: 'إنستاباي • فوري • فيزا',
      whatsapp: 'دعم واتساب',
      whatsappDesc: 'دعم مباشر عبر واتساب لأصحاب المطاعم. احصل على المساعدة عندما تحتاجها.',
      whatsappTag: 'دعم 24/7',
      compliance: 'الامتثال المحلي',
      complianceDesc: 'متوافق تماماً مع اللوائح المصرية وقوانين حماية البيانات.',
      complianceTag: 'متوافق مع مصر',
      integratedWith: 'متكامل مع مزودي الدفع المحليين',
    },
    contact: {
      badge: 'ابدأ الآن',
      title: 'حوّل مطعمك اليوم',
      description: 'لا تدع الأنظمة القديمة تعيق عملك. انضم لثورة تجربة الطعام وشاهد كيف يمكن لقوت تحويل تجربة عملائك.',
      freeDemo: 'عرض توضيحي واستشارة مجانية',
      noCommitment: 'لا يوجد التزام مطلوب',
      customSolution: 'حل مخصص لاحتياجاتك',
      localSupport: 'دعم محلي بالعربية والإنجليزية',
      preferDirect: 'تفضل التواصل مباشرة؟',
      email: 'البريد الإلكتروني:',
      whatsapp: 'واتساب:',
      formTitle: 'اطلب عرض توضيحي',
      restaurantName: 'اسم المطعم',
      restaurantPlaceholder: 'مثال: مشويات القاهرة',
      yourName: 'اسمك',
      namePlaceholder: 'الاسم الكامل',
      emailLabel: 'البريد الإلكتروني',
      emailPlaceholder: 'you@email.com',
      phone: 'الهاتف',
      phonePlaceholder: '+20 1XX XXX XXXX',
      location: 'الموقع',
      selectLocation: 'اختر موقعك',
      message: 'رسالة (اختياري)',
      messagePlaceholder: 'أخبرنا عن مطعمك وما تبحث عنه...',
      submit: 'اطلب عرض',
      submitting: 'جاري الإرسال...',
      agreement: 'بالإرسال، أنت توافق على أن يتواصل معك فريق قوت.',
      thankYou: 'شكراً لك!',
      thankYouDesc: 'لقد استلمنا طلبك وسنتواصل معك خلال 24 ساعة.',
      submitAnother: 'أرسل طلباً آخر',
      required: '*',
    },
    footer: {
      tagline: 'نحوّل الضيافة في مصر بحلول الطعام الرقمي الذكية. قوائم ذكية. مدفوعات ذكية. تجربة طعام أذكى.',
      quickLinks: 'روابط سريعة',
      contactUs: 'تواصل معنا',
      ceo: 'أحمد علام، الرئيس التنفيذي',
      location: 'القاهرة الجديدة، مصر',
      copyright: '© 2025 قوت. جميع الحقوق محفوظة.',
      bottomTagline: 'نحوّل الضيافة في مصر',
    },
  },
};

export default LanguageContext;

